### ISSUE TITLE
AWS setup - RStudio container setup test

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/minidream-r-env#12]
Test RStudio environment setup:

- [x] users can login to RStudio environment w/ default password and username
- [x] users can change their default password and username and are still able to login in RStudio environment 
- [x] users see module contents in their RStudio environment (after running James' broadcast modules script)
- [x] admin user can update module content in RStudio environment across users' directories 
- [x] module solution submission and evaluation works (can use module0 since it's very simple)
- [x] leaderboard on Synapse reflects module submissions

**Comment by BrunoGrandePhD** [comment]
I've tested the submission process with Module 0, which seems to partially work. The [submission file](https://www.synapse.org/#!Synapse:syn25872449) was uploaded to the appropriate Synapse folder. However, I then run into the following error:
```
Error in value[[3L]](cond) : 403 Client Error: 
User lacks SUBMIT access to Evaluation 9614774
```

If I go to [scoreboard](https://www.synapse.org/#!Synapse:syn25653150/wiki/610099) for Module 0, I get the following (presumably related) error:
```
Sorry, you do not have sufficient privileges for access. Insufficient permissions to read from Synapse object 9614774
```

I can confirm that I'm on the "2021 CSBC PS-ON mini-Dream Participants" Synapse [team](https://www.synapse.org/#!Team:3425824). From what I can tell, @lopierra has access to the evaluation queue. So, the above might be fixed by granting the participants team with submit permission on the evaluation queue. 
```
GET https://repo-prod.prod.sagebase.org/repo/v1/evaluation/9614774/acl

{
  "id": "9614774",
  "creationDate": "2021-05-03T17:35:10.755Z",
  "etag": "97ef7eeb-c495-4aeb-be93-4cd7b2b8a440",
  "resourceAccess": [
    {
      "principalId": 3423548,  # Pierette's principal ID
      "accessType": [
        "READ_PRIVATE_SUBMISSION",
        "SUBMIT",
        "UPDATE",
        "CHANGE_PERMISSIONS",
        "CREATE",
        "DELETE",
        "READ",
        "DELETE_SUBMISSION",
        "UPDATE_SUBMISSION"
      ]
    }
  ]
}
```

I also wonder if the admins need to be given specific permission to evaluate submissions in the queue. I'm not getting an error when running `challenge_eval.sh`, but I don't know if I should expect a fatal error if I lack permission.

**Comment by thomasyu888** [comment]
@BrunoGrandePhD the admins can be given "can score" privilege on synapse to pull the submissions down.  The above issue can definitely be fixed by giving the participant team "can submit" permissions.

Note to view the scoreboard, you can actually create submissions views now which take queue ids as the scope.  Let me know if you have any questions.

**Comment by lopierra** [comment]
Sorry, I didn't realize I had to set separate permissions for the challenge (I thought it inherited from the Project). I added the Admins team with "administrator" privilege, and the Participants team with "can submit."

**Comment by BrunoGrandePhD** [comment]
Thanks, @thomasyu888 and @lopierra! With the new permissions, I was able to submit to the evaluation queue from RStudio. 
```
> submission <- submit_module_answers(module = 0)
################################################## Uploading file to Synapse storage ##################################################
Successfully submitted file: 'bgrande_activity-0.yml'
... stored as 'syn25872449'
Submission ID: '9712317
```

After making sure that I was logged in, I think I got the evaluation code running. However, nothing appears on the corresponding [scoreboard](https://www.synapse.org/#!Synapse:syn25653150/wiki/610099). Does this have to do with the fact that the challenge hasn't been "launched" yet (_i.e._ the "Run Challenge" button hasn't been clicked yet). 
```
python3 challenge.py   -u "bgrande" -u "mnikolov" -u "lopierra"   --send-messages --notifications score --all


 ===========================================================================
2021-06-10T16:56:13.071555
Welcome, Bruno Grande!



Scoring  9614774 2021 CSBC PS-ON mini-DREAM Challenge
------------------------------------------------------------


done:  2021-06-10T16:56:13.354889
=========================================================================== 
```

**Comment by BrunoGrandePhD** [comment]
Never mind. I just got the email below. I'm going to fix the R dependencies (which are outside of the R container. 
```
Traceback (most recent call last):
File "/home/bgrande/minidream-challenge/scoring_harness/challenge.py", line 291, in score
score, message = conf.score_submission(evaluation, submission)
File "/home/bgrande/minidream-challenge/scoring_harness/challenge_config.py", line 157, in score_submission
score = config['scoring_func'](submission)
File "/home/bgrande/minidream-challenge/scoring_harness/challenge_config.py", line 88, in score
robjects.r("source('%s')" % filePath)
File "/home/bgrande/miniconda3/envs/minidream-2021/lib/python3.9/site-packages/rpy2/robjects/__init__.py", line 438, in __call__
res = self.eval(p)
File "/home/bgrande/miniconda3/envs/minidream-2021/lib/python3.9/site-packages/rpy2/robjects/functions.py", line 198, in __call__
return (super(SignatureTranslatedFunction, self)
File "/home/bgrande/miniconda3/envs/minidream-2021/lib/python3.9/site-packages/rpy2/robjects/functions.py", line 125, in __call__
res = super(Function, self).__call__(*new_args, **new_kwargs)
File "/home/bgrande/miniconda3/envs/minidream-2021/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
cdata = function(*args, **kwargs)
File "/home/bgrande/miniconda3/envs/minidream-2021/lib/python3.9/site-packages/rpy2/rinterface.py", line 680, in __call__
raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in library(yaml) : there is no package called ‘yaml’
```
