### ISSUE TITLE
AWS setup - RStudio container setup test

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/minidream-r-env#24]
Distilled from #12 

**Test RStudio environment setup:**

- [x]  users can login to RStudio environment w/ default password and username
- [x]  users can change their default password and username and are still able to login in RStudio environment
- [x]  users see module contents in their RStudio environment (after running James' broadcast modules script)
- [x]  admin user can update module content in RStudio environment across users' directories
- [x]  module solution submission and evaluation works (can use module0 since it's very simple)
- [x]  leaderboard on Synapse reflects module submissions

Please refer to the detailed troubleshooting in #12 for peculiarities fo the Synapse Challenge Submission Queues + Permissions.

**Comment by linglp** [comment]
@ychae  I could not check the check boxes in this issue. Could you give me a higher level of permission on this repo?

**Comment by milen-sage** [comment]
@linglp I added FAIR Data's team to the repo as maintainers. You should have access now?

**Comment by milen-sage** [comment]
Thanks @linglp! I was also able to login and play around with module 0.

**Comment by linglp** [comment]
Tests summary: 
1. Add users/change password
- Admins were added by using the script: `docker compose exec rstudio root/utils/add_users.sh /admin.csv`.  Admin.csv is kept local since that it contains password. I also tested by changing my default password for username `linglp` using command `passwd` in R studio terminal 
- I could also log in by using other people's default admin password 
2. Broadcast module: I am also able to broadcast module 0 by using `broadcast_module.sh` script. Full command is here: `docker compose exec rstudio root/utils/broadcast_module.sh /shared/modules/module0 rstudio-user` 
3. Module submission: I could submit to both 2021 and 2022 minidream submission synapse folder

**Comment by linglp** [comment]
*Note*: `broadcast.sh` could not delete content. I tried to add a testing folder in module 0 and re-broadcasted module 0. But I could still see my testing folder in R studio environment. 

The main command in broadcast_module.sh is rsync -ur ([source](https://github.com/Sage-Bionetworks/minidream-r-env/blob/bgrande/minidream-2021/rstudio/utils/broadcast_module.sh#L26)). Without the --delete option, rsync will not delete extraneous files from the destination. We will need to manually delete testing folder/file

**Comment by linglp** [comment]
Note: delete an empty folder for all users: 
`docker exec rstudio find /home -name testing-folder -delete`

**Comment by linglp** [comment]
Documentation can be found here: https://github.com/Sage-Bionetworks/minidream-r-env/tree/lpeng/minidream-2022

**Comment by milen-sage** [comment]
This is awesome! Thanks @linglp!

**Comment by linglp** [comment]
@ychae Yes. Thanks for reminding me
